version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test-linux:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - run:
          name: clang install version 9
          command: |
            sudo apt-get update
            sudo apt-get install clang-9
            sudo apt-get install libc++-9-dev
            sudo apt-get install libc++abi-9-dev
      - checkout
      - run: 'sudo apt remove --purge --auto-remove cmake'
      - run:
          name: cmake install version 3.18.3
          command: |
            version=3.18.3
            build=1
            mkdir ~/temp
            cd ~/temp
            wget https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3-Linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo sh cmake-3.18.3-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
            sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
            cd /
            cmake --version
      - run:
          name: build
          command: |
            sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 100
            sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 100
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j$(nproc)
      - run:
          name: test
          command: ./build/tests/tests
  
  build-and-test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: cmake install version 3.18.3
          command: |
            mkdir C:\cmake
            cd C:\cmake
            curl.exe -L -o cmake.zip "https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3-win64-x64.zip"
            Write-Output "cmake.zip has been downloaded"
            tar -xf cmake.zip
            ls
            cd .\cmake-3.18.3-win64-x64\bin
            .\cmake --version
      - run: 
          name: build
          command: |
            $env:Path += ";C:\cmake\cmake-3.18.3-win64-x64\bin"
            cmake -G "Visual Studio 16 2019" -A x64 -B build
            cmake --build ./build --config Release
            ls build
      - run: 
        name: test
        command: ./tests/tests
workflows:
 version: 2.1
# build_and_test-linux:
#   jobs:
 #    - build-and-test-linux

 build_and_test-windows:
   jobs:
 #    - build-and-test-linux
      - build-and-test-windows
